### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by StuartIanNaylor** [s60sc/ESP-BOX_firmware_Alexa#1]
Tried Alexa and works fine never did get round to trying if the 34mm mic spacing makes much difference.
Speed of sound is 343 m / s so divide by 16k is 21.5mm so likely the 16mm diff (less than a sample) will make little diff is not exact.

Dunno if you noticed but the 4 channel ADC provides ref channel sync as guess there must be latency in the i2s stream as AEC can be very clock sensitive.
I noticed this with speex as using different soundcards and clocks kills speex aec and the dev notes of speex highlight that pretty strongly so guess MASE is the same.
In the forum it was suggested it was due to DAC distortion that the input I2S could not be used for ref, I doubt that very much as the amp, speaker & room distortion will be huge in comparison.

Prob is with compiled blob libs is it stops much tinkering as if the clock latency of mic & ref could be matched as presume its just a few clocks, then maybe a hardware loopback would not be needed as pretty sure its there for sync and not dac distortion.

I have been wondering if tflite-micro is going to be optimised for the s3 as it seems to have more layer capacity and xtensa even have a LSTM that I think would run on S3.
I think there are better models that likely would run DS-CNN from https://github.com/google-research/google-research/tree/master/kws_streaming is one but really if LSTM is an option then CRNN like multinet is a good option for streaming KWS and having control of the dataset is really advantageous as if you save the signature and collate local data you can run additional epochs of actual use to really up accuracy.
Its strange multinet is CRNN based as ESP-DL seems to lack both LSTM or GRU or do the convert tools work even if layers are not implicit in the ESP32-DL layers?

Thinking about it if the mic i2s stream was an incrementing number then the 1st number 1 at the dac would have the clock count  at mic input.
Dunno sure there is a way to measure the input stream clock latency as really struggling to source cost effective quad channel ADC's and pretty sure the necessary sync can be worked out in software.

**Comment by s60sc** [comment]
My use case is for simple voice commands to control an esp32 application.
Adding new multinet voice commands using included tool to convert phrase text into phoneme text is straightforward and has good recognition.
