### ISSUE TITLE
How did you did it?

### ISSUE THREAD

**Issue by sajov** [s60sc/ESP-BOX_firmware_Alexa#2]
Hi, @s60sc   I’m new to esp devices and even programming c.
I have a esp32-s3-box and esp-korvo.
I was able to install/update firmware but I search for a starting point to add Mqtt in addition to demo functions.
It seem that platformio, audrino and esphome Doesn’t  support this board. Even if then I’m not able by now to get this demo functions developed. 
so customizing Demos is the way to go.
How you did it?

**Comment by s60sc** [comment]
You have to use the IDF IDE 
https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/tutorial/install.md

**Comment by sajov** [comment]
This I haven’t tried, thanks
